apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-elasticsearch
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: elasticsearch
    targetRevision: 22.1.6
    helm:
      values: |
        global:
          security:
            allowInsecureImages: true
        security:
          enabled: false
          tls:
            restEncryption: false
        image:
          repository: bitnamilegacy/elasticsearch
        sysctlImage:
          repository: bitnamilegacy/os-shell
        volumePermissions:
          image:
            repository: bitnamilegacy/os-shell
        master:
          replicaCount: 1
          resources:
            requests:
              cpu: 150m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 2Gi
          heapSize: 512m
          persistence:
            enabled: true
            size: 8Gi
        data:
          replicaCount: 1
          resources:
            requests:
              cpu: 250m
              memory: 384Mi
            limits:
              cpu: "2"
              memory: 4Gi
          heapSize: 1g
          persistence:
            enabled: true
            size: 8Gi
        coordinating:
          replicaCount: 0
        ingest:
          enabled: false
        service:
          type: NodePort
          nodePorts:
            restAPI: "30920"
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
