apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 16.7.27
    helm:
      values: |
        global:
          security:
            allowInsecureImages: true
        auth:
          username: nacos
          password: Sherlock8962.
          database: nacos
        image:
          registry: docker.io
          repository: bitnamilegacy/postgresql
          tag: 17.6.0-debian-12-r4
        primary:
          persistence:
            enabled: true
            size: 8Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true