apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-redis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 21.2.3
    helm:
      values: |
        global:
          security:
            allowInsecureImages: true
        architecture: standalone
        auth:
          enabled: true
          password: Sherlock8962.
        image:
          registry: docker.io
          repository: bitnamilegacy/redis
          tag: 8.0.2-debian-12-r3
        master:
          persistence:
            enabled: true
            size: 8Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true