apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nginx
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-nginx
  template:
    metadata:
      labels:
        app: demo-nginx
    spec:
      imagePullSecrets:
        - name: harbor-pull
      containers:
        - name: app
          image: harbor.local:8443/demo/nginx:9af27ff2e2f7690a4f8eaad13dca49e7bbc2ab5c
          ports:
            - containerPort: 8888